
name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'my-snowflake-db'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
models:
  my_new_project:
      # Applies to all files under models/example/
      Source:
          materialized: table
      intermediate:
          materialized: ephemeral
