version: 2
models:
    - name: stg_student_profile
      description: "Table contains all the information about the students"
      columns:
          - name: std_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
 
    - name: stg_student_Results
      description: "Table contains the student results info"
      columns:
          - name: std_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                - relationships:
                    to: ref('stg_student_profile')
                    field: std_id
                - only_numbers
          - name: result
            description: "Result of a student"
            tests:      
                - accepted_values:
                    values: ['Pass', 'Fail']