version: 2

models:
  - name: dim_customer_details
    description: '{{doc("DIM_CUSTOMER_DETAILS")}}'
    columns:
        - name: Employee_id
          tests:
              - not_null
              # used macros to checks for only number in column
              - only_numbers
        - name: First_name
          tests:
              - not_null
        - name: middle_name
          tests:
              # used macros to checks at least one value is present
              - test_at_least_one
        - name: Last_name
          tests:
              - not_null
        - name: contact_number
          tests:
              - not_null
        - name: customer_id
          tests:
              - not_null
              - unique
        - name: order_id
          tests:
              - not_null
              - unique
        - name: date_order
          tests:
              - not_null
        - name: quantity
          tests:
              - not_null
        - name: price
          tests:
              - not_null
        - name: phone_number
          tests:
              - not_null
              - unique
  
  - name: dim_custDiscount
    description: '{{doc("DIM_CUSDISCOUNT")}}'
    columns:
        - name: Quantity
          tests:
              - not_null
              # used macros to checks for only number in column
              - only_numbers

                   
                    