WITH DISCOUNTS AS (
    SELECT *
    FROM {{ source('FROZENSYSTEM', 'TBLORDER') }}
    WHERE 
    QUANTITY > 2 AND (SELECT (price/(Select Avg(price) FROM {{ source('FROZENSYSTEM', 'TBLORDER') }})) ) 

)
SELECT
    DATE_ORDER AS ORDER_DATE,
    PRICE AS AMOUNT,
    QUANTITY,
    ID
FROM DISCOUNTS
ORDER BY 2